:PROPERTIES:
:ID:       311d357b-70c3-4867-b03c-bf60944acf7e
:ANKI_DECK: Main
:END:
#+title: Smell
#+filetags: :Psychology:

* Olfactory System
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic (and reversed card)
:ANKI_NOTE_ID: 1731990436376
:END:
Responsible for our sense of smell. It works by detecting chemical molecules in the air and converting them into neural signals—a process called [[id:385b5840-dda2-4e88-b4c4-c32883eb57d0][transduction]].

* Olfactory System Process
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:ANKI_NOTE_ID: 1732067700594
:END:
1. Molecules from scents in the air (like perfume or food) enter the nose and dissolve in the mucus of the olfactory epithelium (a tissue at the top of the nasal cavity).
2. These molecules stimulate olfactory receptors on specialized neurons, which then send signals to the olfactory bulb in the brain.
3. Unlike other senses, olfactory signals bypass the thalamus and go directly to areas in the limbic system and olfactory cortex, which are linked to emotion and memory. This explains why certain smells can trigger emotional memories.
